version: "3.5"

services:

  DB0001:
    restart: always
    image: percona:5.7
    env_file:
      - .mysql-dev-env
    volumes:
      - ./data/db01/mysql:/var/lib/mysql:cached
    ports:
      - 3301:3306


  DB0002:
    restart: always
    image: percona:5.7
    env_file:
      - .mysql-dev-env
    volumes:
      - ./data/db02/mysql:/var/lib/mysql:cached
    ports:
      - 3302:3306


  DB0003:
    restart: always
    image: percona:5.7
    env_file:
      - .mysql-dev-env
    volumes:
      - ./data/db03/mysql:/var/lib/mysql:cached
    ports:
      - 3303:3306


  DB0004:
    restart: always
    image: percona:5.7
    env_file:
      - .mysql-dev-env
    volumes:
      - ./data/db04/mysql:/var/lib/mysql:cached
    ports:
      - 3304:3306


  DB0005:
    restart: always
    image: percona:5.7
    env_file:
      - .mysql-dev-env
    volumes:
      - ./data/db05/mysql:/var/lib/mysql:cached
    ports:
      - 3305:3306


  DB0006:
    restart: always
    image: percona:5.7
    env_file:
      - .mysql-dev-env
    volumes:
      - ./data/db06/mysql:/var/lib/mysql:cached
    ports:
      - 3306:3306


  DB0007:
    restart: always
    image: postgres
    env_file:
      - .postgres-dev-env
    volumes:
      - ./data/db07/postgres:/data/postgres
    ports:
      - 5407:5432

  gothreaded:
    image: jrsaunders/gothreaded
    restart: always
    environment:
      GOTHREADED_DEBUG: "true"
    ports:
      - 1534:1534

  pdocache:
    container_name: pdocache
    image: redis
    restart: always
    volumes:
      - ./data:/data
    entrypoint: redis-server --appendonly yes
    ports:
      - 6379:6379


