<?php


namespace ShardMatrix\DB;



use Illuminate\Database\Query\Builder;
use ShardMatrix\Uuid;

class PaginationQuery extends Query {


	protected Builder $builder;

	protected ?Uuid $lastUuid = null;


	/**
	 * @param Uuid|null $lastUuid
	 *
	 * @return PaginationQuery
	 */
	public function setLastUuid( ?Uuid $lastUuid ): PaginationQuery {
		$this->lastUuid = $lastUuid;
		return $this;
	}

	public function getSql(): string {
		return parent::getSql(); // TODO: Change the autogenerated stub
	}

	public function getBinds(): ?array {
		return parent::getBinds(); // TODO: Change the autogenerated stub
	}
}